version: '3.8'

networks:
  ghostwire:
    driver: bridge

services:
  
  c2_server:
    build: ./C2_Server
    ports:
      - "80:80"
    networks:
      - ghostwire

  c2:
    build: ./C2
    networks:
      - ghostwire
    stdin_open: true
    tty: true
    
    environment:
      TERM: xterm

      
     



     
